---
title: 'Assignment 2: Caching the Inverse of a Matrix'
author: "antekai"
date: "Friday, July 25, 2014"
output:
  html_document:
    highlight: textmate
    keep_md: yes
---
To view KNITcachematrix.html in Github
```{r}
#add   http://htmlpreview.github.io/?  to the beginning of html file URL
```
or [click here](http://htmlpreview.github.io/?https://github.com/antekai/ProgrammingAssignment2/blob/master/KNITcachematrix.html)

#

### cachematrix.R
```{r}
## The code creates a list of functions.
makeCacheMatrix <- function(x = matrix()) {
  ## set the internal variable to null
  inverseMatrix <- NULL 
  ## creating the set function to assign the incoming matrix to the internal variable
  set <- function(y) { 
    x <<- y
    ## clearing the internal variable
    inverseMatrix <<- NULL #
  }
  ## reading the value the the incoming matrix to the variable get
  get <- function() x 
  ## assigning the internal variable to the cacheSolve variable
  setsolve <- function(solve) {
    inverseMatrix <<- solve 
  }
  ## reassigning the internal variables, the keep all the variables
  getsolve <- function() inverseMatrix 
  
  list(set = set, get = get,
       setsolve = setsolve,
       getsolve = getsolve)
}

## The following set of instructions create the inverse matrix using the solve 
## function and also stores the value for quick recall of the cached value

cacheSolve <- function(x, ...) {
  ## receiving the incoming matrix
  inverseMatrix <- x$getsolve() 
  ## if the internal variable is not null, the following message will be passed
  ## along with the cached data, saving cpu time
  ## checking the value of the internal variable
  if(!is.null(inverseMatrix)) { 
    message("getting cached data")
    return(inverseMatrix)
  }
  
  ## These following set of instructions are executed only when a new variable is passed
  
  ## reading the matrix into a local variable data
  data <- x$get() 
  ## performing the time/cpu sensitive operation solve to invert the matrix
  inverseMatrix <- solve(data, ...) 
  ## assigning the calculated value to the solved variable
  x$setsolve(inverseMatrix) 
  ## returning the internal variable with the solved variable to the parent function
  inverseMatrix 
}
```



##Testing cachematrix.R

### Simple case (2x2 matrix)
```{r}
e<-matrix(c(2,2,3,4),nrow=2,ncol=2,byrow=T)
e
solve(e)
y<-makeCacheMatrix(e)
cacheSolve(y)
```
Correct!

### Random large matrix (1000x1000 matrix)
```{r}
nrows <- 1000
ncols <- 1000
x <- stats::rnorm(nrows*ncols)
dim(x) <- c(nrows, ncols)
y <- makeCacheMatrix(x)
solved_with_caching_solve <- cacheSolve(y)
solved_with_solve <- solve(x)
identical(solved_with_caching_solve, solved_with_solve)
```
TRUE!

